apiVersion: v1
kind: Service
metadata:
  name: homepages-service
spec:
  selector:
    app: homepages-pod
  ports:
  - port: 8085
    nodePort: 30885
    protocol: TCP
    targetPort: 80
  type: NodePort
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepages-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: shorturl-pod
  template:
    metadata:
      labels:
        app: homepages-pod
    spec:
      containers:
      - name: homepages-container
        image: homepages:v1
        resources:
          limits:
            memory: "64Mi"
            cpu: "25m"
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: Production
        ports:
        - containerPort: 80
          protocol: TCP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: homepages-ingress
 annotations:
   kubernetes.io/ingress.class: "nginx"
   nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: trustmacus.com
   http:
     paths:
     - path: /
       pathType: Prefix
       backend:
         service:
           name: homepages-service
           port:
             number: 80